/* GENERATED by build/icons-build.mjs — do not edit. */
export type IconSize = 20 | 24 | 48;
export interface IconArt { body: string; accent: string }
export interface IconDef {
  name: IconName;
  /** Paint the accent under the body: a tick on a disc, not a disc on a tick. */
  accentFirst: boolean;
  /** False for glyphs with nowhere to put an accent: chevrons, x, plus. */
  hasAccent: boolean;
  outline: Partial<Record<IconSize, IconArt>>;
  filled: Partial<Record<IconSize, IconArt>>;
}
export type IconName =
  | 'alert-circle'
  | 'alert-triangle'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-left-right'
  | 'arrow-right'
  | 'arrow-up'
  | 'arrow-up-down'
  | 'ban'
  | 'bar-chart'
  | 'battery-full'
  | 'bell'
  | 'blocks'
  | 'book-open'
  | 'box'
  | 'boxes'
  | 'building'
  | 'calendar-clock'
  | 'check'
  | 'check-circle'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'clipboard-check'
  | 'clipboard-list'
  | 'clock'
  | 'copy'
  | 'dashboard'
  | 'download'
  | 'external-link'
  | 'eye'
  | 'file-spreadsheet'
  | 'file-text'
  | 'filter'
  | 'grip-vertical'
  | 'hand'
  | 'home'
  | 'info'
  | 'inventory'
  | 'keyboard'
  | 'layers'
  | 'list-checks'
  | 'list-ordered'
  | 'loader'
  | 'lock'
  | 'log-out'
  | 'map-pin'
  | 'minus'
  | 'more-vertical'
  | 'navigation'
  | 'package'
  | 'package-check'
  | 'package-plus'
  | 'panel-left-close'
  | 'panel-left-open'
  | 'pencil'
  | 'phone'
  | 'pin'
  | 'pin-off'
  | 'play'
  | 'play-circle'
  | 'plug'
  | 'plus'
  | 'printer'
  | 'refresh'
  | 'repeat'
  | 'rotate-ccw'
  | 'save'
  | 'scan-line'
  | 'scissors'
  | 'search'
  | 'send'
  | 'settings'
  | 'settings-2'
  | 'shield'
  | 'shield-alert'
  | 'shield-check'
  | 'shield-off'
  | 'shopping-bag'
  | 'shopping-cart'
  | 'signal-high'
  | 'sliders'
  | 'sparkles'
  | 'split'
  | 'star'
  | 'store'
  | 'thumbs-down'
  | 'thumbs-up'
  | 'trash'
  | 'trending-up'
  | 'truck'
  | 'undo'
  | 'upload'
  | 'user'
  | 'users'
  | 'wand'
  | 'warehouse'
  | 'wifi'
  | 'x'
  | 'x-circle'
  | 'zap';
export declare const AlertCircle: IconDef;
export declare const AlertTriangle: IconDef;
export declare const ArrowDown: IconDef;
export declare const ArrowLeft: IconDef;
export declare const ArrowLeftRight: IconDef;
export declare const ArrowRight: IconDef;
export declare const ArrowUp: IconDef;
export declare const ArrowUpDown: IconDef;
export declare const Ban: IconDef;
export declare const BarChart: IconDef;
export declare const BatteryFull: IconDef;
export declare const Bell: IconDef;
export declare const Blocks: IconDef;
export declare const BookOpen: IconDef;
export declare const Box: IconDef;
export declare const Boxes: IconDef;
export declare const Building: IconDef;
export declare const CalendarClock: IconDef;
export declare const Check: IconDef;
export declare const CheckCircle: IconDef;
export declare const ChevronDown: IconDef;
export declare const ChevronLeft: IconDef;
export declare const ChevronRight: IconDef;
export declare const ClipboardCheck: IconDef;
export declare const ClipboardList: IconDef;
export declare const Clock: IconDef;
export declare const Copy: IconDef;
export declare const Dashboard: IconDef;
export declare const Download: IconDef;
export declare const ExternalLink: IconDef;
export declare const Eye: IconDef;
export declare const FileSpreadsheet: IconDef;
export declare const FileText: IconDef;
export declare const Filter: IconDef;
export declare const GripVertical: IconDef;
export declare const Hand: IconDef;
export declare const Home: IconDef;
export declare const Info: IconDef;
export declare const Inventory: IconDef;
export declare const Keyboard: IconDef;
export declare const Layers: IconDef;
export declare const ListChecks: IconDef;
export declare const ListOrdered: IconDef;
export declare const Loader: IconDef;
export declare const Lock: IconDef;
export declare const LogOut: IconDef;
export declare const MapPin: IconDef;
export declare const Minus: IconDef;
export declare const MoreVertical: IconDef;
export declare const Navigation: IconDef;
export declare const Package: IconDef;
export declare const PackageCheck: IconDef;
export declare const PackagePlus: IconDef;
export declare const PanelLeftClose: IconDef;
export declare const PanelLeftOpen: IconDef;
export declare const Pencil: IconDef;
export declare const Phone: IconDef;
export declare const Pin: IconDef;
export declare const PinOff: IconDef;
export declare const Play: IconDef;
export declare const PlayCircle: IconDef;
export declare const Plug: IconDef;
export declare const Plus: IconDef;
export declare const Printer: IconDef;
export declare const Refresh: IconDef;
export declare const Repeat: IconDef;
export declare const RotateCcw: IconDef;
export declare const Save: IconDef;
export declare const ScanLine: IconDef;
export declare const Scissors: IconDef;
export declare const Search: IconDef;
export declare const Send: IconDef;
export declare const Settings: IconDef;
export declare const Settings2: IconDef;
export declare const Shield: IconDef;
export declare const ShieldAlert: IconDef;
export declare const ShieldCheck: IconDef;
export declare const ShieldOff: IconDef;
export declare const ShoppingBag: IconDef;
export declare const ShoppingCart: IconDef;
export declare const SignalHigh: IconDef;
export declare const Sliders: IconDef;
export declare const Sparkles: IconDef;
export declare const Split: IconDef;
export declare const Star: IconDef;
export declare const Store: IconDef;
export declare const ThumbsDown: IconDef;
export declare const ThumbsUp: IconDef;
export declare const Trash: IconDef;
export declare const TrendingUp: IconDef;
export declare const Truck: IconDef;
export declare const Undo: IconDef;
export declare const Upload: IconDef;
export declare const User: IconDef;
export declare const Users: IconDef;
export declare const Wand: IconDef;
export declare const Warehouse: IconDef;
export declare const Wifi: IconDef;
export declare const X: IconDef;
export declare const XCircle: IconDef;
export declare const Zap: IconDef;
export declare const ICONS: Record<IconName, IconDef>;
export declare const LIBRARY_VERSION: string;
